// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptFile(arg1) {
  return window['go']['main']['App']['DecryptFile'](arg1);
}

export function EncryptFile(arg1) {
  return window['go']['main']['App']['EncryptFile'](arg1);
}

export function GenerateKey() {
  return window['go']['main']['App']['GenerateKey']();
}

export function RunBenchmark(arg1) {
  return window['go']['main']['App']['RunBenchmark'](arg1);
}

export function SelectInputFile() {
  return window['go']['main']['App']['SelectInputFile']();
}

export function SelectOutputFile(arg1) {
  return window['go']['main']['App']['SelectOutputFile'](arg1);
}
