// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DecryptFile(arg1:main.DecryptRequest):Promise<main.DecryptResult>;

export function EncryptFile(arg1:main.EncryptRequest):Promise<main.EncryptResult>;

export function GenerateKey():Promise<string>;

export function RunBenchmark(arg1:string):Promise<Array<main.BenchmarkResult>>;

export function SelectInputFile():Promise<string>;

export function SelectOutputFile(arg1:string):Promise<string>;
